### ISSUE TITLE
Ideas / To-Do

### ISSUE THREAD

**Issue by rsokl** [rsokl/phantom-tensors#1]
To Do:
- [x] Support parsing for variable-length tensors: `parse(..., Tensor[*T])`
- [x] Handle scalars (empty shapes)
- [x] Add support for `Any` dim (important! -- TypeVarTuples are currently invariant!)
- [x] Support arbitrary generics (in progress)
- [x] Only bind on NewTypes (e.g. `EvenInt` shouldn't bind to a specific value)
- [x] Run type checking on readme
- [ ] Enable `tuple` and `int` support in `parse` 
- [x] Remove explicit dependency on phantom-types (😢 ) and implement custom `__isinstance__` instead
- [x] Support `Literal[num]`
- [x] Support int-based phantom types within shape annotations (e.g. to provide size constraints)
- [ ] Do basic benchmarking
- [ ] Add caching
- [x] Improve ergonomics with  `phantom_tensors.alphabet` and `phantom_tensors.words`
- [x] Add CI
- [ ] Make `ParseError` messages really nice
- [x] Upload to pypi
- [ ] Write basic docs

Ideas:
- [ ] Support for hypothesis
- [ ] Think about how broadcasting might work.. special names?
- [ ] Ship auto-phantom function
- [ ] Enable isolated scopes for `dim_binding_scope`
